language: generic
script:
 - |
    if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
      #####TRAVIS_COMMIT_MESSAGE
      pull_request_url=https://github.com/pulse360-lab/rtb-telegram-bot/pulls
      message="----- ðŸ“˜ ðŸ“Ÿ ------------------------------\n"
      message+="New pull request is opened\n"
      message+="From user: $(dirname ${TRAVIS_REPO_SLUG})\n"
      message+="From branch: ${TRAVIS_PULL_REQUEST_BRANCH}\n\n"
      message+="Commit Message: ${TRAVIS_COMMIT_MESSAGE}"
      message+="${pull_request_url}"
      
      curl -X POST \
            -d chat_id=${GROUP_TELEGRAM_ID} \
            -d text="$(echo -e ${message})" \
            https://api.telegram.org/bot${ODROID_TELEGRAM_BOT_TOKEN}/sendMessage
    fi
branches:
  only:
    - develop
    - patch
    - master
